# Copyright 2017-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.4

EAPI=6

CRATES="
aho-corasick-0.5.3
bitflags-0.4.0
bitflags-0.6.0
bitflags-0.7.0
bitflags-0.9.1
c_vec-1.2.1
cairo-rs-0.2.0
cairo-sys-rs-0.4.0
cfg-if-0.1.2
dbus-0.4.1
dbus-macros-0.0.6
dlib-0.3.1
dtoa-0.4.2
dummy-rustwlc-0.6.5
env_logger-0.3.5
fixedbitset-0.1.8
fuchsia-zircon-0.2.1
fuchsia-zircon-sys-0.2.0
gcc-0.3.54
gdk-pixbuf-0.2.0
gdk-pixbuf-sys-0.4.0
getopts-0.2.15
gio-sys-0.4.0
glib-0.3.1
glib-sys-0.4.0
gobject-sys-0.4.0
itoa-0.3.4
json_macro-0.1.1
kernel32-sys-0.2.2
lazy_static-0.2.9
libc-0.2.33
libloading-0.3.4
log-0.3.8
memchr-0.1.11
nix-0.6.0
nix-0.8.1
num-traits-0.1.40
ordermap-0.3.0
petgraph-0.4.10
phf-0.7.21
phf_codegen-0.7.21
phf_generator-0.7.21
phf_shared-0.7.21
pkg-config-0.3.9
rand-0.3.18
regex-0.1.80
regex-syntax-0.3.9
rlua-0.9.7
rustc-serialize-0.3.24
rustc_version-0.1.7
rustwlc-0.6.4
semver-0.1.20
serde-0.9.15
serde_json-0.9.10
siphasher-0.2.2
target_build_utils-0.3.1
thread-id-2.0.0
thread_local-0.2.7
utf8-ranges-0.1.3
uuid-0.3.1
void-1.0.2
way-cooler-0.6.2
wayland-scanner-0.9.10
wayland-server-0.9.10
wayland-sys-0.6.0
wayland-sys-0.9.10
winapi-0.2.8
winapi-build-0.1.1
xcb-0.8.1
xml-rs-0.6.1
"

inherit eutils cargo git-r3

DESCRIPTION="Customizeable Wayland compositor written in Rust"
EGIT_REPO_URI="https://github.com/Immington-Industries/way-cooler/"
HOMEPAGE=$EGIT_REPO_URI
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MIT" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

RDEPEND=""
DEPEND="dev-libs/wlc
	>=virtual/rust-1.17.0"

src_unpack() {
	git-r3_src_unpack
	cargo_src_unpack
}

src_install() {
	cargo_src_install
}
